# Generated by Django 5.1 on 2024-10-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Catador', 'Catador'), ('Tecnico', 'Tecnico'), ('Barista', 'Barista')], max_length=20)),
            ],
        ),
    ]
