# Generated by Django 5.1 on 2024-09-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='fechaSalida',
            field=models.DateField(auto_now=True),
        ),
    ]
